language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- jruby

install: script/bootstrap
script: script/cibuild
before_install:
    - gem update --system
    - gem install bundler
    - sudo update-ca-certificates
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
