title: Módulo de procesamiento de audio
description: Un proyecto de Alejandro Higuera C para INTRO CS UN-2026573 2020-1S.
show_downloads: true

baseurl: "/AudioProcessing" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://alejandrohiguera.codes" # change this to the base hostname & protocol for your site


google_analytics: UA-171784808-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Alejandro Higuera Castro
image: /thumbnail-jumbo.png
twitter:
  username: ahc1029

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['notebook', 'acerca', 'instalacion']
